// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TN.DVDCentral.PL2.Data;

#nullable disable

namespace TN.DVDCentral.PL2.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    partial class DVDCentralEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e0f3f22-d753-4b95-84a6-3bbb2577de75"),
                            UserId = new Guid("1c3534b6-dbd6-45d5-af1e-4534dcaac405")
                        },
                        new
                        {
                            Id = new Guid("217e0167-d876-46e0-8bd3-ff26ffae89e3"),
                            UserId = new Guid("c54d37de-62c6-4618-b9b3-572d63889e20")
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblCartItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("663198c8-fcdc-49a1-9436-a678c572215f"),
                            CartId = new Guid("5e0f3f22-d753-4b95-84a6-3bbb2577de75"),
                            MovieId = new Guid("bbddac5e-72c3-4db1-a50b-8498f7f117d8"),
                            Qty = 1
                        },
                        new
                        {
                            Id = new Guid("12734636-a0cf-4354-b26a-d114cb4c2ac0"),
                            CartId = new Guid("5e0f3f22-d753-4b95-84a6-3bbb2577de75"),
                            MovieId = new Guid("8f9158df-1e1b-41dc-bfbc-d6e9a3e8c205"),
                            Qty = 2
                        },
                        new
                        {
                            Id = new Guid("f3e1c648-88ff-4e94-94c6-4dd2090a28f9"),
                            CartId = new Guid("217e0167-d876-46e0-8bd3-ff26ffae89e3"),
                            MovieId = new Guid("8f9158df-1e1b-41dc-bfbc-d6e9a3e8c205"),
                            Qty = 1
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f2ee76d-ba8f-45ca-b75a-8ec8b7e3fffa"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("1c3534b6-dbd6-45d5-af1e-4534dcaac405"),
                            ZIP = "54935"
                        },
                        new
                        {
                            Id = new Guid("639275be-b8a6-4e2b-8f21-ce776eb0069a"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("c54d37de-62c6-4618-b9b3-572d63889e20"),
                            ZIP = "56495"
                        },
                        new
                        {
                            Id = new Guid("8eb43006-d60a-499d-9291-a7a89027a1a3"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("76efa159-4f92-48d7-9f04-6ceb36ae1274"),
                            ZIP = "53142"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b412454f-e32b-4802-a49e-7fab9d38fbaa"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("257781ec-41e0-4d10-9204-77501af48611"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("f53ae989-0583-4190-b7a2-f51b50e67875"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("5f4bde64-23db-4596-aa07-5be5732a090a"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("02de908a-06a8-4b2a-835b-14482b08a4db"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("21742ace-b696-4917-a60b-f607172500b6"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("237d70f8-5956-4ac6-ab86-4ff80b50e10a"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("28da639c-13fc-4c10-8cb8-c40241c7b2b7"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("9a7ae84f-b5eb-4e84-8f79-6da6ad11cdae"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("2fce2f29-ca74-477d-9675-e22ebd29d551"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a6d5011-b53f-4aca-93c7-3982805670ac"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("eb0da3e9-b2c0-4e8c-9e60-b77652619057"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("30250b51-de3d-4c31-9945-baa42b4045e6"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("552e90f2-7ba5-4a63-98ce-b22af2e5b2e0"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("94115536-2970-479e-8b75-104e1a2754d5"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("f79941bf-4261-4d77-b1e0-eac40a351d33"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("c1a0c9ba-c006-40e6-9d96-0b47e0af0aa9"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("46d6c105-e800-46d1-b2b0-f0f79ec5c68b"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("07bf4cd3-f31d-46ef-9d38-7448e2de7843"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("1163ca18-4826-44b3-a4f2-5d22c5949b82"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbddac5e-72c3-4db1-a50b-8498f7f117d8"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("b412454f-e32b-4802-a49e-7fab9d38fbaa"),
                            FormatId = new Guid("237d70f8-5956-4ac6-ab86-4ff80b50e10a"),
                            ImagePath = "Rocky.jpg",
                            Quantity = 2,
                            RatingId = new Guid("865591cf-df4e-4e6f-aece-c3865a7422f9"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("1dacec1f-deaf-41d1-932b-acd6f228cf56"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("b412454f-e32b-4802-a49e-7fab9d38fbaa"),
                            FormatId = new Guid("237d70f8-5956-4ac6-ab86-4ff80b50e10a"),
                            ImagePath = "Rocky.jpg",
                            Quantity = 2,
                            RatingId = new Guid("865591cf-df4e-4e6f-aece-c3865a7422f9"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("8f9158df-1e1b-41dc-bfbc-d6e9a3e8c205"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("257781ec-41e0-4d10-9204-77501af48611"),
                            FormatId = new Guid("28da639c-13fc-4c10-8cb8-c40241c7b2b7"),
                            ImagePath = "Jaws1.jpg",
                            Quantity = 1,
                            RatingId = new Guid("f6945cd3-a39e-4dcb-b98f-4bd584adba0c"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("8a29e702-8646-4690-8da0-833aa6bb13a1"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("f53ae989-0583-4190-b7a2-f51b50e67875"),
                            FormatId = new Guid("9a7ae84f-b5eb-4e84-8f79-6da6ad11cdae"),
                            ImagePath = "PrincessBride.jpg",
                            Quantity = 4,
                            RatingId = new Guid("7bcb352a-c319-4a7c-8fec-0e9550cb92df"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("dc3b2c9f-0efb-4ffa-831d-774555c20b24"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("5f4bde64-23db-4596-aa07-5be5732a090a"),
                            FormatId = new Guid("9a7ae84f-b5eb-4e84-8f79-6da6ad11cdae"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            Quantity = 2,
                            RatingId = new Guid("e0869197-fded-4543-938c-020d04491f9a"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("401e3be3-9cdb-4f8e-afa2-8973cf6d57fb"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("257781ec-41e0-4d10-9204-77501af48611"),
                            FormatId = new Guid("28da639c-13fc-4c10-8cb8-c40241c7b2b7"),
                            ImagePath = "StarWarsNewHope.jpg",
                            Quantity = 1,
                            RatingId = new Guid("f6945cd3-a39e-4dcb-b98f-4bd584adba0c"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("b5485a28-b011-4e79-b6b8-de99f874ce69"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("257781ec-41e0-4d10-9204-77501af48611"),
                            FormatId = new Guid("28da639c-13fc-4c10-8cb8-c40241c7b2b7"),
                            ImagePath = "PaleRider.jpg",
                            Quantity = 1,
                            RatingId = new Guid("f6945cd3-a39e-4dcb-b98f-4bd584adba0c"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("008f0fcb-be1f-46eb-97e3-bca76f1f4351"),
                            GenreId = new Guid("30250b51-de3d-4c31-9945-baa42b4045e6"),
                            MovieId = new Guid("bbddac5e-72c3-4db1-a50b-8498f7f117d8")
                        },
                        new
                        {
                            Id = new Guid("241dcadb-8377-4362-82f2-eaed8c0085e5"),
                            GenreId = new Guid("552e90f2-7ba5-4a63-98ce-b22af2e5b2e0"),
                            MovieId = new Guid("bbddac5e-72c3-4db1-a50b-8498f7f117d8")
                        },
                        new
                        {
                            Id = new Guid("6be222ff-7695-43fe-977c-a89cf732fefb"),
                            GenreId = new Guid("f79941bf-4261-4d77-b1e0-eac40a351d33"),
                            MovieId = new Guid("bbddac5e-72c3-4db1-a50b-8498f7f117d8")
                        },
                        new
                        {
                            Id = new Guid("0b86b8b1-b76b-40ea-a1fb-bcf2200730e6"),
                            GenreId = new Guid("30250b51-de3d-4c31-9945-baa42b4045e6"),
                            MovieId = new Guid("8f9158df-1e1b-41dc-bfbc-d6e9a3e8c205")
                        },
                        new
                        {
                            Id = new Guid("150e4d37-fb9f-459f-bac1-dc983c5443bd"),
                            GenreId = new Guid("552e90f2-7ba5-4a63-98ce-b22af2e5b2e0"),
                            MovieId = new Guid("8f9158df-1e1b-41dc-bfbc-d6e9a3e8c205")
                        },
                        new
                        {
                            Id = new Guid("f7438bbc-30ad-4646-963e-069914e6f908"),
                            GenreId = new Guid("9a6d5011-b53f-4aca-93c7-3982805670ac"),
                            MovieId = new Guid("8a29e702-8646-4690-8da0-833aa6bb13a1")
                        },
                        new
                        {
                            Id = new Guid("44ebbb48-f120-47c9-b860-7d755a829e7d"),
                            GenreId = new Guid("eb0da3e9-b2c0-4e8c-9e60-b77652619057"),
                            MovieId = new Guid("8a29e702-8646-4690-8da0-833aa6bb13a1")
                        },
                        new
                        {
                            Id = new Guid("69dd79d3-6fd6-4411-b081-69ca78a1ff6c"),
                            GenreId = new Guid("f79941bf-4261-4d77-b1e0-eac40a351d33"),
                            MovieId = new Guid("8a29e702-8646-4690-8da0-833aa6bb13a1")
                        },
                        new
                        {
                            Id = new Guid("33769060-6657-499f-9b55-694d686d52dc"),
                            GenreId = new Guid("552e90f2-7ba5-4a63-98ce-b22af2e5b2e0"),
                            MovieId = new Guid("dc3b2c9f-0efb-4ffa-831d-774555c20b24")
                        },
                        new
                        {
                            Id = new Guid("daecb85f-d306-4787-ae52-860d05baf909"),
                            GenreId = new Guid("f79941bf-4261-4d77-b1e0-eac40a351d33"),
                            MovieId = new Guid("dc3b2c9f-0efb-4ffa-831d-774555c20b24")
                        },
                        new
                        {
                            Id = new Guid("890572a1-5484-4c0c-baa8-53f22f8c878e"),
                            GenreId = new Guid("552e90f2-7ba5-4a63-98ce-b22af2e5b2e0"),
                            MovieId = new Guid("401e3be3-9cdb-4f8e-afa2-8973cf6d57fb")
                        },
                        new
                        {
                            Id = new Guid("d9366dfc-4f6b-4f32-97d2-4f35036e2f45"),
                            GenreId = new Guid("c1a0c9ba-c006-40e6-9d96-0b47e0af0aa9"),
                            MovieId = new Guid("401e3be3-9cdb-4f8e-afa2-8973cf6d57fb")
                        },
                        new
                        {
                            Id = new Guid("cbab7362-4132-4c1e-a214-49a20c325175"),
                            GenreId = new Guid("46d6c105-e800-46d1-b2b0-f0f79ec5c68b"),
                            MovieId = new Guid("b5485a28-b011-4e79-b6b8-de99f874ce69")
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("95101d80-5af1-4f08-94ea-f222064e581b"),
                            CustomerId = new Guid("639275be-b8a6-4e2b-8f21-ce776eb0069a"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("c54d37de-62c6-4618-b9b3-572d63889e20")
                        },
                        new
                        {
                            Id = new Guid("cfc0ca9f-6290-4d1a-88b4-958ed0c82756"),
                            CustomerId = new Guid("8eb43006-d60a-499d-9291-a7a89027a1a3"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("c54d37de-62c6-4618-b9b3-572d63889e20")
                        },
                        new
                        {
                            Id = new Guid("5775792d-d638-46d6-ae1c-1b8584f3f84d"),
                            CustomerId = new Guid("8eb43006-d60a-499d-9291-a7a89027a1a3"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("76efa159-4f92-48d7-9f04-6ceb36ae1274")
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9b68375-d259-4232-ba93-02045fbaca5e"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("bbddac5e-72c3-4db1-a50b-8498f7f117d8"),
                            OrderId = new Guid("95101d80-5af1-4f08-94ea-f222064e581b"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("dc1f2fba-3980-4f4e-89d0-40e7e512f9d9"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("8f9158df-1e1b-41dc-bfbc-d6e9a3e8c205"),
                            OrderId = new Guid("95101d80-5af1-4f08-94ea-f222064e581b"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("a5deca7e-4c7d-415f-997e-1441bea3c465"),
                            Cost = 10.99,
                            MovieId = new Guid("8f9158df-1e1b-41dc-bfbc-d6e9a3e8c205"),
                            OrderId = new Guid("cfc0ca9f-6290-4d1a-88b4-958ed0c82756"),
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("865591cf-df4e-4e6f-aece-c3865a7422f9"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("f6945cd3-a39e-4dcb-b98f-4bd584adba0c"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("7bcb352a-c319-4a7c-8fec-0e9550cb92df"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("e0869197-fded-4543-938c-020d04491f9a"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("07949f29-e64e-4489-aeb6-952603f93e09"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c3534b6-dbd6-45d5-af1e-4534dcaac405"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "smarin"
                        },
                        new
                        {
                            Id = new Guid("c54d37de-62c6-4618-b9b3-572d63889e20"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("76efa159-4f92-48d7-9f04-6ceb36ae1274"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "bfoote"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblCart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblDirector", "Director")
                        .WithMany("tblMovies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_DirectorId");

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblFormat", "Format")
                        .WithMany("tblMovies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_FormatId");

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblRating", "Rating")
                        .WithMany("tblMovies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblGenre", "Genre")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Navigation("tblMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
