// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TN.DVDCentral.PL2.Data;

#nullable disable

namespace TN.DVDCentral.PL2.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    partial class DVDCentralEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5c1a522-aed1-4784-8c09-a6912df2527e"),
                            UserId = new Guid("72b5640f-6736-40e5-a7f2-d885ab379dd6")
                        },
                        new
                        {
                            Id = new Guid("524baa50-12ac-4c0b-9110-f18358b17e30"),
                            UserId = new Guid("c31b0ca5-678e-4c8b-bb00-3c556c770146")
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblCartItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7eb59df-0b88-45f6-9be9-122eb85703d5"),
                            CartId = new Guid("d5c1a522-aed1-4784-8c09-a6912df2527e"),
                            MovieId = new Guid("84367a0f-5e58-4087-a55c-55dade74ff02"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("4642ea04-63d9-499d-b106-0d1521d38459"),
                            CartId = new Guid("d5c1a522-aed1-4784-8c09-a6912df2527e"),
                            MovieId = new Guid("bd30859c-bed0-40e1-af8a-4f2b1fb86d70"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("02b852b0-25f6-4998-bb60-4d408e0750f5"),
                            CartId = new Guid("524baa50-12ac-4c0b-9110-f18358b17e30"),
                            MovieId = new Guid("bd30859c-bed0-40e1-af8a-4f2b1fb86d70"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b02bae9d-977d-467d-bf3a-43bbc082537b"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("72b5640f-6736-40e5-a7f2-d885ab379dd6"),
                            ZIP = "54935"
                        },
                        new
                        {
                            Id = new Guid("37d74e40-ec42-4599-a664-325ea6061d08"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("c31b0ca5-678e-4c8b-bb00-3c556c770146"),
                            ZIP = "56495"
                        },
                        new
                        {
                            Id = new Guid("64966745-1d86-4338-950b-e3347a29c2b5"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("a861a8d5-e5ee-43f9-b8ee-1d639529934b"),
                            ZIP = "53142"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1e5ca89-8771-43b4-8cef-05c73d4442ca"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("f92b54f7-b982-412e-afaf-e2c006c2d65e"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("faef9a92-ff19-4f0b-86dc-5e9eae9f1e7d"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("c231fa86-5313-4999-b909-ff3e0af56886"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("e1471dd2-1546-4487-aeae-03755e594fc6"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("86671109-aa71-402b-9359-44e9538e589f"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("31380c4f-730c-4dcb-bc0d-1bfe8c0c6271"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("176ec3d1-589c-4e26-a718-f5380eb81ee9"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("5fb3347f-776a-4f15-bfb1-092d0a452c34"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("a32ff621-4995-4e36-b465-29e3167d1710"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52407425-23e4-47d7-b402-45e60ce9bee5"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("aed3f82d-1785-4a97-b90a-8a99c5be539e"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("1979a458-e21b-4d9c-a94b-10a1f26bd7b6"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("4eb99a2e-6e61-4813-a7b3-e382ce91f6d7"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("246bb906-a3ce-427b-a3ab-075c7a20d805"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("6fe9ee31-e218-4f64-b092-2be21b1ce115"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("cd985c01-bf35-4d94-9d11-787eb48c1c16"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("35b91b59-efde-4940-89d8-73d140cb656c"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("31ae5e72-05b3-427c-a220-4e907f6bffde"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("72613e03-06f6-488a-9d04-301a08fd7a41"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("84367a0f-5e58-4087-a55c-55dade74ff02"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("f1e5ca89-8771-43b4-8cef-05c73d4442ca"),
                            FormatId = new Guid("31380c4f-730c-4dcb-bc0d-1bfe8c0c6271"),
                            ImagePath = "Rocky.jpg",
                            Quantity = 2,
                            RatingId = new Guid("96c87ade-554c-4768-b71a-bcac405a9b56"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("271bafbd-9427-4d31-83b5-ef0c640945ca"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("f1e5ca89-8771-43b4-8cef-05c73d4442ca"),
                            FormatId = new Guid("31380c4f-730c-4dcb-bc0d-1bfe8c0c6271"),
                            ImagePath = "Rocky.jpg",
                            Quantity = 2,
                            RatingId = new Guid("96c87ade-554c-4768-b71a-bcac405a9b56"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("bd30859c-bed0-40e1-af8a-4f2b1fb86d70"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("f92b54f7-b982-412e-afaf-e2c006c2d65e"),
                            FormatId = new Guid("176ec3d1-589c-4e26-a718-f5380eb81ee9"),
                            ImagePath = "Jaws1.jpg",
                            Quantity = 1,
                            RatingId = new Guid("3a1db43e-1054-4fd6-b68f-b4cfa31befec"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("f0d83531-5c27-4151-8396-55f7c470b393"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("faef9a92-ff19-4f0b-86dc-5e9eae9f1e7d"),
                            FormatId = new Guid("5fb3347f-776a-4f15-bfb1-092d0a452c34"),
                            ImagePath = "PrincessBride.jpg",
                            Quantity = 4,
                            RatingId = new Guid("83bea5ae-6ce1-4e14-aab7-7b022ea2cd4e"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("9479327c-e16e-459d-86e8-bfa4a18e008e"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("c231fa86-5313-4999-b909-ff3e0af56886"),
                            FormatId = new Guid("5fb3347f-776a-4f15-bfb1-092d0a452c34"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            Quantity = 2,
                            RatingId = new Guid("f2890847-1bfa-4833-aefd-858bf51fc19a"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("4b1dd22b-d861-4c72-9c4b-20afb04f3fe6"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("f92b54f7-b982-412e-afaf-e2c006c2d65e"),
                            FormatId = new Guid("176ec3d1-589c-4e26-a718-f5380eb81ee9"),
                            ImagePath = "StarWarsNewHope.jpg",
                            Quantity = 1,
                            RatingId = new Guid("3a1db43e-1054-4fd6-b68f-b4cfa31befec"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("076313f0-89c5-47ee-a4fc-bd12d0a99705"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("f92b54f7-b982-412e-afaf-e2c006c2d65e"),
                            FormatId = new Guid("176ec3d1-589c-4e26-a718-f5380eb81ee9"),
                            ImagePath = "PaleRider.jpg",
                            Quantity = 1,
                            RatingId = new Guid("3a1db43e-1054-4fd6-b68f-b4cfa31befec"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7e932ae-55d3-4469-afb8-a347d253c396"),
                            GenreId = new Guid("1979a458-e21b-4d9c-a94b-10a1f26bd7b6"),
                            MovieId = new Guid("84367a0f-5e58-4087-a55c-55dade74ff02")
                        },
                        new
                        {
                            Id = new Guid("2326c3ce-0aec-461c-bcbb-1711a32b506e"),
                            GenreId = new Guid("4eb99a2e-6e61-4813-a7b3-e382ce91f6d7"),
                            MovieId = new Guid("84367a0f-5e58-4087-a55c-55dade74ff02")
                        },
                        new
                        {
                            Id = new Guid("3a1eea23-4d5f-4f5f-b26c-11e8bf97c231"),
                            GenreId = new Guid("6fe9ee31-e218-4f64-b092-2be21b1ce115"),
                            MovieId = new Guid("84367a0f-5e58-4087-a55c-55dade74ff02")
                        },
                        new
                        {
                            Id = new Guid("76c6de8e-5a2d-4ee3-897a-5b88dbef6c06"),
                            GenreId = new Guid("1979a458-e21b-4d9c-a94b-10a1f26bd7b6"),
                            MovieId = new Guid("bd30859c-bed0-40e1-af8a-4f2b1fb86d70")
                        },
                        new
                        {
                            Id = new Guid("2571b956-2911-4ebb-b6f8-69558e32dd30"),
                            GenreId = new Guid("4eb99a2e-6e61-4813-a7b3-e382ce91f6d7"),
                            MovieId = new Guid("bd30859c-bed0-40e1-af8a-4f2b1fb86d70")
                        },
                        new
                        {
                            Id = new Guid("cbf09478-4e41-49db-85c6-1f38db039cc6"),
                            GenreId = new Guid("52407425-23e4-47d7-b402-45e60ce9bee5"),
                            MovieId = new Guid("f0d83531-5c27-4151-8396-55f7c470b393")
                        },
                        new
                        {
                            Id = new Guid("c723eedc-7a48-4778-9e2f-0fcdd03b2ce6"),
                            GenreId = new Guid("aed3f82d-1785-4a97-b90a-8a99c5be539e"),
                            MovieId = new Guid("f0d83531-5c27-4151-8396-55f7c470b393")
                        },
                        new
                        {
                            Id = new Guid("1a118625-d5a3-42f5-94e1-49274a9fb497"),
                            GenreId = new Guid("6fe9ee31-e218-4f64-b092-2be21b1ce115"),
                            MovieId = new Guid("f0d83531-5c27-4151-8396-55f7c470b393")
                        },
                        new
                        {
                            Id = new Guid("f5151936-a93b-40c8-80c9-18eb82c80764"),
                            GenreId = new Guid("4eb99a2e-6e61-4813-a7b3-e382ce91f6d7"),
                            MovieId = new Guid("9479327c-e16e-459d-86e8-bfa4a18e008e")
                        },
                        new
                        {
                            Id = new Guid("ab983a2a-f5c5-4468-8e2d-8e3edf2e4a29"),
                            GenreId = new Guid("6fe9ee31-e218-4f64-b092-2be21b1ce115"),
                            MovieId = new Guid("9479327c-e16e-459d-86e8-bfa4a18e008e")
                        },
                        new
                        {
                            Id = new Guid("4d636480-338c-4417-9fe5-3329589f8f64"),
                            GenreId = new Guid("4eb99a2e-6e61-4813-a7b3-e382ce91f6d7"),
                            MovieId = new Guid("4b1dd22b-d861-4c72-9c4b-20afb04f3fe6")
                        },
                        new
                        {
                            Id = new Guid("9958c788-468e-4d0c-80ea-7f44901c2d60"),
                            GenreId = new Guid("cd985c01-bf35-4d94-9d11-787eb48c1c16"),
                            MovieId = new Guid("4b1dd22b-d861-4c72-9c4b-20afb04f3fe6")
                        },
                        new
                        {
                            Id = new Guid("e67e52ee-5529-4a46-82f0-2a81849f45a1"),
                            GenreId = new Guid("35b91b59-efde-4940-89d8-73d140cb656c"),
                            MovieId = new Guid("076313f0-89c5-47ee-a4fc-bd12d0a99705")
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("87ba3640-4da1-4b6c-89da-ce45699622a4"),
                            CustomerId = new Guid("37d74e40-ec42-4599-a664-325ea6061d08"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("c31b0ca5-678e-4c8b-bb00-3c556c770146")
                        },
                        new
                        {
                            Id = new Guid("d33870c6-d44a-46f3-9cee-7db0af7a97c9"),
                            CustomerId = new Guid("64966745-1d86-4338-950b-e3347a29c2b5"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("c31b0ca5-678e-4c8b-bb00-3c556c770146")
                        },
                        new
                        {
                            Id = new Guid("8df20bf0-6978-461c-a236-685be51ca6b2"),
                            CustomerId = new Guid("64966745-1d86-4338-950b-e3347a29c2b5"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("a861a8d5-e5ee-43f9-b8ee-1d639529934b")
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("98f32354-d98d-46e1-bd8d-9babe48cba2d"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("84367a0f-5e58-4087-a55c-55dade74ff02"),
                            OrderId = new Guid("87ba3640-4da1-4b6c-89da-ce45699622a4"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f7142e48-af23-41c4-b1c6-d9be8d885d7e"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("bd30859c-bed0-40e1-af8a-4f2b1fb86d70"),
                            OrderId = new Guid("87ba3640-4da1-4b6c-89da-ce45699622a4"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("ec53639b-3c9a-4c14-bb67-2954a2609e49"),
                            Cost = 10.99,
                            MovieId = new Guid("bd30859c-bed0-40e1-af8a-4f2b1fb86d70"),
                            OrderId = new Guid("d33870c6-d44a-46f3-9cee-7db0af7a97c9"),
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96c87ade-554c-4768-b71a-bcac405a9b56"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("3a1db43e-1054-4fd6-b68f-b4cfa31befec"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("83bea5ae-6ce1-4e14-aab7-7b022ea2cd4e"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("f2890847-1bfa-4833-aefd-858bf51fc19a"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("8aa41446-2acc-40ac-aaf6-bb3c3b79b308"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("72b5640f-6736-40e5-a7f2-d885ab379dd6"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "smarin"
                        },
                        new
                        {
                            Id = new Guid("c31b0ca5-678e-4c8b-bb00-3c556c770146"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("a861a8d5-e5ee-43f9-b8ee-1d639529934b"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "bfoote"
                        });
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblCart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblDirector", "Director")
                        .WithMany("tblMovies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_DirectorId");

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblFormat", "Format")
                        .WithMany("tblMovies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_FormatId");

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblRating", "Rating")
                        .WithMany("tblMovies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblGenre", "Genre")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblOrder", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblCustomer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblOrderItem", b =>
                {
                    b.HasOne("TN.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany("OrderItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TN.DVDCentral.PL2.Entities.tblOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblCustomer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TN.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Navigation("tblMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
